server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1
spring:
  profiles:
    active: dev
  application:
    name: service-article-html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/


website:
  domain-name: imoocnews.com


freemarker:
  html:
    target: html/freemarker_html
    article: /Users/qianzhikang/Dev/tomcat/apache-tomcat-9.0.74/webapps/imooc-news/portal/a/