server:
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1
spring:
  profiles:
    active: dev
  application:
    name: service-article
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imooc.pojo
website:
  domain-name: imoocnews.com