server:
  port: 8001
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-news-dev
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
  rabbitmq:
    host: 8.130.88.119
    port: 5672
    username: admin
    password: admin
    virtual-host: imooc-news-dev
  data:
    mongodb:
      uri: mongodb://root:root@8.130.88.119:27017
      database: imooc-news


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl